"""Aarvia career navigation and job application package."""

from .discovery import create_profile, generate_open_questions
from .discovery_state import DiscoveryState, FollowUpStatus, load_discovery_state
from .profile import (
    BasicProfile,
    CareerPreferences,
    CareerProfile,
    Constraints,
    Education,
    ExperienceOverview,
    ProfileValidationError,
    Skill,
)
from .storage import load_profile, save_profile
from .catalog_build import (
    CatalogBuildResult,
    CatalogDraft,
    RoleSample,
    build_catalog_draft,
    deduplicate_sources,
    load_catalog_draft,
    prevalence_for_counts,
    save_catalog_draft,
)
from .career_direction import (
    ProfileReference,
    RecommendationSet,
    RoleGapAnalysis,
    UserRoleDecision,
    load_recommendation_set,
    load_role_gap_analysis,
    load_user_role_decision,
    save_recommendation_set,
    save_role_gap_analysis,
    save_user_role_decision,
)
from .live_jobs import (
    ApplicationURLStatus,
    LiveJobCollection,
    load_live_job_collection,
    save_live_job_collection,
)
from .jd_curation import (
    CurationArtifact,
    RequirementCandidate,
    load_curation_artifact,
    save_curation_artifact,
)
from .jd_sources import (
    JDSource,
    JDSourceCollection,
    ListingStatus,
    SourceTier,
    content_sha256,
    generate_canonical_job_id,
    generate_source_id,
    load_jd_source_collection,
    save_jd_source_collection,
)
from .role_catalog import (
    Phase2ValidationError,
    RoleCatalog,
    RoleFamily,
    RoleRequirement,
    SourceReference,
    load_role_catalog,
    production_role_catalog,
    save_role_catalog,
)

__version__ = "0.6.2"

__all__ = [
    "BasicProfile",
    "ApplicationURLStatus",
    "CatalogBuildResult",
    "CatalogDraft",
    "CareerPreferences",
    "CareerProfile",
    "Constraints",
    "CurationArtifact",
    "Education",
    "DiscoveryState",
    "ExperienceOverview",
    "FollowUpStatus",
    "ProfileValidationError",
    "ProfileReference",
    "Phase2ValidationError",
    "RecommendationSet",
    "RoleCatalog",
    "RoleFamily",
    "RoleGapAnalysis",
    "RoleRequirement",
    "Skill",
    "SourceReference",
    "LiveJobCollection",
    "JDSource",
    "JDSourceCollection",
    "ListingStatus",
    "RequirementCandidate",
    "RoleSample",
    "SourceTier",
    "UserRoleDecision",
    "create_profile",
    "build_catalog_draft",
    "content_sha256",
    "deduplicate_sources",
    "generate_canonical_job_id",
    "generate_source_id",
    "generate_open_questions",
    "load_profile",
    "load_catalog_draft",
    "load_curation_artifact",
    "load_jd_source_collection",
    "load_live_job_collection",
    "load_recommendation_set",
    "load_role_catalog",
    "load_role_gap_analysis",
    "load_user_role_decision",
    "load_discovery_state",
    "production_role_catalog",
    "prevalence_for_counts",
    "save_profile",
    "save_catalog_draft",
    "save_curation_artifact",
    "save_jd_source_collection",
    "save_live_job_collection",
    "save_recommendation_set",
    "save_role_catalog",
    "save_role_gap_analysis",
    "save_user_role_decision",
]
