from copy import deepcopy

import pytest

from aarvia.jd_sources import (
    ExperienceRange,
    JDSourceCollection,
    content_sha256,
    generate_source_id,
    load_jd_source_collection,
    normalize_jd_content,
    save_jd_source_collection,
)
from aarvia.role_catalog import Phase2ValidationError
from phase2b_fixtures import source_collection_data, source_data


def test_content_hash_normalization_is_versioned_and_deterministic() -> None:
    first = "  Qualifications  \r\nUse Ｐｙｔｈｏｎ.   \r\n\r\n"
    second = "  Qualifications\nUse Python.\n"

    assert normalize_jd_content(first) == second
    assert content_sha256(first) == content_sha256(second)
    with pytest.raises(Phase2ValidationError, match="unsupported"):
        content_sha256(first, version="jd-text-v2")


@pytest.mark.parametrize(
    "value",
    [
        {"status": "explicit", "minimum_years": 0, "maximum_years": 2},
        {"status": "not_stated", "minimum_years": None, "maximum_years": None},
        {"status": "ambiguous", "minimum_years": None, "maximum_years": None},
    ],
)
def test_experience_range_keeps_explicit_unknown_and_ambiguous_distinct(value) -> None:
    assert ExperienceRange.from_dict(value).status.value == value["status"]


def test_not_stated_experience_cannot_silently_become_zero_years() -> None:
    with pytest.raises(Phase2ValidationError, match="non-explicit"):
        ExperienceRange.from_dict(
            {"status": "not_stated", "minimum_years": 0, "maximum_years": None}
        )

    data = source_data()
    data["experience_range"] = {"status": "explicit", "minimum_years": 0, "maximum_years": 3}
    with pytest.raises(Phase2ValidationError, match="more than two years"):
        JDSourceCollection.from_dict(source_collection_data([data]))


def test_source_id_must_be_generated_by_aarvia() -> None:
    data = source_data()
    data["source_id"] = "provider_supplied_id"
    with pytest.raises(Phase2ValidationError, match="generated by Aarvia"):
        JDSourceCollection.from_dict(source_collection_data([data]))

    expected = generate_source_id(
        data["source_url"],
        platform_name=data["platform_name"],
        platform_job_id=data["platform_job_id"],
    )
    assert expected.startswith("src_")


def test_tier_a_b_and_c_valid_combinations() -> None:
    collection = JDSourceCollection.from_dict(
        source_collection_data(
            [
                source_data(1),
                source_data(2, tier="tier_b_verified_platform"),
                source_data(3, tier="tier_c_discovery_only"),
            ]
        )
    )
    assert [item.source_tier.value for item in collection.sources] == [
        "tier_a_official",
        "tier_b_verified_platform",
        "tier_c_discovery_only",
    ]


def test_tier_b_requires_platform_job_id_application_and_verification() -> None:
    for field in ("platform_job_id", "application_url", "last_verified_at"):
        data = source_data(tier="tier_b_verified_platform")
        data[field] = None
        if field == "platform_job_id":
            data["source_id"] = generate_source_id(
                data["source_url"], platform_name=data["platform_name"], platform_job_id=None
            )
        with pytest.raises(Phase2ValidationError, match="Tier B"):
            JDSourceCollection.from_dict(source_collection_data([data]))


def test_source_verification_cannot_precede_capture() -> None:
    data = source_data()
    data["captured_at"] = "2026-09-01T12:00:00+00:00"
    data["last_verified_at"] = "2026-09-01T11:59:59+00:00"
    with pytest.raises(Phase2ValidationError, match="cannot precede captured_at"):
        JDSourceCollection.from_dict(source_collection_data([data]))


def test_careers_homepage_is_tier_a_but_not_a_specific_posting() -> None:
    data = source_data(source_type="official_career_page")
    data["exact_job_title"] = None
    data["canonical_job_id"] = None
    collection = JDSourceCollection.from_dict(source_collection_data([data]))
    assert collection.sources[0].source_type.value == "official_career_page"


def test_platform_redirect_and_official_source_share_one_canonical_job() -> None:
    official = source_data(1)
    platform = source_data(
        1,
        tier="tier_b_verified_platform",
        canonical_job_id=official["canonical_job_id"],
        canonical_source_reference=official["source_id"],
    )
    platform["verification_method"] = "platform_redirect_to_official"
    official["discovery_source_references"] = [platform["source_id"]]

    collection = JDSourceCollection.from_dict(source_collection_data([official, platform]))
    assert len({item.canonical_job_id for item in collection.sources}) == 1


def test_source_collection_strict_round_trip_and_failure_preservation(tmp_path, monkeypatch) -> None:
    value = JDSourceCollection.from_dict(source_collection_data([source_data()]))
    path = save_jd_source_collection(value, tmp_path / "sources.json")
    duplicate = save_jd_source_collection(value, tmp_path / "copy.json")
    assert load_jd_source_collection(path) == value
    assert path.read_bytes() == duplicate.read_bytes()

    original = path.read_bytes()
    monkeypatch.setattr("aarvia.phase2_storage.os.replace", lambda *_: (_ for _ in ()).throw(OSError("replace failed")))
    with pytest.raises(OSError, match="replace failed"):
        save_jd_source_collection(value, path)
    assert path.read_bytes() == original


def test_schema_two_is_explicit_and_rejects_schema_one_shape() -> None:
    data = source_collection_data([source_data()])
    data["schema_version"] = 1
    with pytest.raises(Phase2ValidationError, match="unsupported JD Source"):
        JDSourceCollection.from_dict(data)

    mixed = deepcopy(source_data())
    mixed["official_url"] = mixed.pop("source_url")
    with pytest.raises(Phase2ValidationError, match="unknown fields"):
        JDSourceCollection.from_dict(source_collection_data([mixed]))
