from copy import deepcopy
from dataclasses import replace

import pytest

from aarvia.jd_curation import (
    CurationArtifact,
    RequirementCandidate,
    load_curation_artifact,
    save_curation_artifact,
)
from aarvia.jd_sources import JDSourceCollection
from aarvia.role_catalog import Phase2ValidationError, production_role_catalog
from phase2b_fixtures import (
    approved_candidate_data,
    curation_data,
    extracted_candidate,
    extraction_metadata,
    source_collection_data,
    source_data,
)


def test_llm_payload_can_only_create_unapproved_candidate() -> None:
    source = source_data()
    candidate = extracted_candidate(source)
    assert candidate.status.value == "candidate_extracted"
    assert candidate.reviewer_decision.value == "pending"
    assert candidate.reviewed_at is None

    payload = {
        "candidate_id": "provider_id",
        "evidence": candidate.evidence.to_dict(),
        "proposed_name": "Python",
        "proposed_description": "Use Python.",
        "proposed_category": "technical_skill",
        "proposed_importance": "core",
        "mapped_role_id": "applied_ai_engineer",
        "mapped_specialization_id": "agentic_ai",
    }
    with pytest.raises(Phase2ValidationError, match="unknown fields: candidate_id"):
        RequirementCandidate.from_extraction(
            payload,
            source_id=source["source_id"],
            source_content_hash=source["content_hash"],
            extraction=extraction_metadata(),
        )

    sources = JDSourceCollection.from_dict(source_collection_data([source]))
    with pytest.raises(Phase2ValidationError, match="generated by Aarvia"):
        replace(candidate, candidate_id="provider_id").validate(
            sources, production_role_catalog()
        )


def test_approved_candidate_requires_complete_human_decision() -> None:
    source = source_data()
    data = approved_candidate_data(source)
    data["decision_reason"] = None
    with pytest.raises(Phase2ValidationError, match="matching reviewer decision"):
        RequirementCandidate.from_dict(data)


def test_candidate_hash_role_and_specialization_cross_references_are_strict() -> None:
    source = source_data()
    sources = JDSourceCollection.from_dict(source_collection_data([source]))
    candidate = RequirementCandidate.from_dict(approved_candidate_data(source))
    candidate.validate(sources, production_role_catalog())

    bad = candidate.to_dict()
    bad["source_content_hash"] = "sha256:" + "0" * 64
    with pytest.raises(Phase2ValidationError, match="content hash"):
        RequirementCandidate.from_dict(bad).validate(sources, production_role_catalog())

    bad = candidate.to_dict()
    bad["mapped_specialization_id"] = "missing_specialization"
    with pytest.raises(Phase2ValidationError, match="unknown specialization"):
        RequirementCandidate.from_dict(bad).validate(sources, production_role_catalog())


def test_curation_requires_consistent_cluster_references() -> None:
    source = source_data()
    sources = JDSourceCollection.from_dict(source_collection_data([source]))
    data = curation_data([source])
    artifact = CurationArtifact.from_dict(data)
    artifact.validate(sources, production_role_catalog())

    data = deepcopy(data)
    data["clusters"][0]["candidate_ids"] = ["missing_candidate"]
    with pytest.raises(Phase2ValidationError, match="inconsistent candidate"):
        CurationArtifact.from_dict(data).validate(sources, production_role_catalog())


def test_confirmed_cluster_requires_human_review_and_evidence() -> None:
    source = source_data()
    data = curation_data([source])
    data["clusters"][0]["decision_reason"] = None
    with pytest.raises(Phase2ValidationError, match="human review metadata"):
        CurationArtifact.from_dict(data)

    data = curation_data([source])
    data["clusters"][0]["candidate_ids"] = []
    with pytest.raises(Phase2ValidationError, match="requires candidates"):
        CurationArtifact.from_dict(data)


def test_curation_typed_round_trip_is_atomic_and_context_validated(tmp_path, monkeypatch) -> None:
    source = source_data()
    sources = JDSourceCollection.from_dict(source_collection_data([source]))
    artifact = CurationArtifact.from_dict(curation_data([source]))
    catalog = production_role_catalog()
    path = save_curation_artifact(
        artifact, tmp_path / "curation.json", sources=sources, catalog=catalog
    )
    copy_path = save_curation_artifact(
        artifact, tmp_path / "copy.json", sources=sources, catalog=catalog
    )
    assert load_curation_artifact(path, sources=sources, catalog=catalog) == artifact
    assert path.read_bytes() == copy_path.read_bytes()

    original = path.read_bytes()
    monkeypatch.setattr("aarvia.phase2_storage.os.replace", lambda *_: (_ for _ in ()).throw(OSError("replace failed")))
    with pytest.raises(OSError, match="replace failed"):
        save_curation_artifact(artifact, path, sources=sources, catalog=catalog)
    assert path.read_bytes() == original


def test_unapproved_candidate_is_valid_curation_data_but_not_approved() -> None:
    source = source_data()
    candidate = extracted_candidate(source)
    data = curation_data([source])
    data["candidates"] = [candidate.to_dict()]
    data["clusters"] = []
    artifact = CurationArtifact.from_dict(data)
    sources = JDSourceCollection.from_dict(source_collection_data([source]))

    artifact.validate(sources, production_role_catalog())
    assert artifact.candidates[0].status.value == "candidate_extracted"
